"""Se agregaron las columnas edad y direccion a la tabla clientes

Revision ID: 04e9eca1bcfc
Revises: 8994df85d936
Create Date: 2026-03-13 14:06:47.870495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e9eca1bcfc'
down_revision: Union[str, Sequence[str], None] = '8994df85d936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('edad', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('direccion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'direccion')
    op.drop_column('clientes', 'edad')
    # ### end Alembic commands ###
