"""actualizacion del campo fecha_registro de la tabla clientes

Revision ID: 79fbc06fe2ce
Revises: fbfd3291a8f1
Create Date: 2026-02-18 12:45:35.359537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79fbc06fe2ce'
down_revision: Union[str, Sequence[str], None] = 'fbfd3291a8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('clientes', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('clientes_email_key'), 'clientes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('clientes_email_key'), 'clientes', ['correo_electronico'], postgresql_nulls_not_distinct=False)
    op.alter_column('clientes', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('clientes', 'fecha_registro',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
