"""Se agrego el campo nombre_completo ala tabla usarios

Revision ID: 839e6bad9d6a
Revises: ddda4cd3c0b1
Create Date: 2026-03-04 12:11:05.891264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839e6bad9d6a'
down_revision: Union[str, Sequence[str], None] = 'ddda4cd3c0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nombre_completo', sa.String(length=50), nullable=False))
    op.alter_column('usuarios', 'correo_electronico',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'usuarios', ['nombre_completo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.alter_column('usuarios', 'correo_electronico',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('usuarios', 'nombre_completo')
    # ### end Alembic commands ###
