"""Se relaciono la tabla usuarios con las tablas clientes, recetas, ordenes_venta y transacciones

Revision ID: 8994df85d936
Revises: 839e6bad9d6a
Create Date: 2026-03-10 18:11:03.237462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8994df85d936'
down_revision: Union[str, Sequence[str], None] = '839e6bad9d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_clientes_usuario_id'), 'clientes', ['usuario_id'], unique=False)
    op.create_foreign_key(None, 'clientes', 'usuarios', ['usuario_id'], ['id'], ondelete='RESTRICT')
    op.add_column('ordenes_venta', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ordenes_venta_usuario_id'), 'ordenes_venta', ['usuario_id'], unique=False)
    op.create_foreign_key(None, 'ordenes_venta', 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
    op.add_column('recetas', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_recetas_usuario_id'), 'recetas', ['usuario_id'], unique=False)
    op.create_foreign_key(None, 'recetas', 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
    op.add_column('transacciones', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_transacciones_usuario_id'), 'transacciones', ['usuario_id'], unique=False)
    op.create_foreign_key(None, 'transacciones', 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
    op.alter_column('recetas','created_at',new_column_name='fecha_creacion',existing_type=sa.TIMESTAMP(timezone=True),server_default=sa.text('now()'),nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transacciones', type_='foreignkey')
    op.drop_index(op.f('ix_transacciones_usuario_id'), table_name='transacciones')
    op.drop_column('transacciones', 'usuario_id')
    op.drop_constraint(None, 'recetas', type_='foreignkey')
    op.drop_index(op.f('ix_recetas_usuario_id'), table_name='recetas')
    op.drop_column('recetas', 'usuario_id')
    op.drop_constraint(None, 'ordenes_venta', type_='foreignkey')
    op.drop_index(op.f('ix_ordenes_venta_usuario_id'), table_name='ordenes_venta')
    op.drop_column('ordenes_venta', 'usuario_id')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_index(op.f('ix_clientes_usuario_id'), table_name='clientes')
    op.drop_column('clientes', 'usuario_id')
    op.alter_column('recetas','fecha_creacion',new_column_name='created_at',existing_type=sa.TIMESTAMP(timezone=True),server_default=sa.text('now()'),nullable=False)
    # ### end Alembic commands ###
