"""Se agregaron las tablas planes_pago y transacciones con relacion a ordenes_venta

Revision ID: 9fa98f4b2f7e
Revises: a4dbb345cc4b
Create Date: 2026-02-25 19:43:16.269297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa98f4b2f7e'
down_revision: Union[str, Sequence[str], None] = 'a4dbb345cc4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_venta_id', sa.Integer(), nullable=False),
    sa.Column('numero_plazos', sa.Integer(), nullable=False),
    sa.Column('frecuencia', sa.String(length=20), nullable=False),
    sa.Column('monto_parcial_sugerido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.CheckConstraint('monto_parcial_sugerido >= 0', name='chk_monto_parcial'),
    sa.CheckConstraint('numero_plazos > 0', name='chk_numero_plazos'),
    sa.ForeignKeyConstraint(['orden_venta_id'], ['ordenes_venta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_pago_orden_venta_id'), 'planes_pago', ['orden_venta_id'], unique=True)
    op.create_table('transacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_venta_id', sa.Integer(), nullable=False),
    sa.Column('monto_abonado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metodo_pago', sa.String(length=30), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.CheckConstraint('monto_abonado > 0', name='chk_monto_abonado'),
    sa.ForeignKeyConstraint(['orden_venta_id'], ['ordenes_venta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacciones_id'), 'transacciones', ['id'], unique=False)
    op.create_index(op.f('ix_transacciones_orden_venta_id'), 'transacciones', ['orden_venta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacciones_orden_venta_id'), table_name='transacciones')
    op.drop_index(op.f('ix_transacciones_id'), table_name='transacciones')
    op.drop_table('transacciones')
    op.drop_index(op.f('ix_planes_pago_orden_venta_id'), table_name='planes_pago')
    op.drop_table('planes_pago')
    # ### end Alembic commands ###
