"""Se agrego la table ordenes_venta con las relaciones

Revision ID: a4dbb345cc4b
Revises: b8565e6b2809
Create Date: 2026-02-18 15:58:24.115511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4dbb345cc4b'
down_revision: Union[str, Sequence[str], None] = 'b8565e6b2809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_pago', sa.String(length=20), nullable=False),
    sa.Column('estado_pago', sa.String(length=20), server_default='PENDIENTE', nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado_pago IN ('PENDIENTE','PAGADO')", name='chk_estado_pago'),
    sa.CheckConstraint("tipo_pago IN ('CONTADO','CREDITO')", name='chk_tipo_pago'),
    sa.CheckConstraint('monto_total >= 0', name='chk_monto_total'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_venta_cliente_id'), 'ordenes_venta', ['cliente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ordenes_venta_cliente_id'), table_name='ordenes_venta')
    op.drop_table('ordenes_venta')
    # ### end Alembic commands ###
