"""Se agrego la table recetas

Revision ID: b8565e6b2809
Revises: 185d3fd1c230
Create Date: 2026-02-18 14:27:43.668556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8565e6b2809'
down_revision: Union[str, Sequence[str], None] = '185d3fd1c230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_consulta', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('od_esfera', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('od_cilindro', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('od_eje', sa.Integer(), nullable=True),
    sa.Column('od_adicion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('oi_esfera', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('oi_cilindro', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('oi_eje', sa.Integer(), nullable=True),
    sa.Column('oi_adicion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('recomendacion_lente', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recetas_cliente_id'), 'recetas', ['cliente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recetas_cliente_id'), table_name='recetas')
    op.drop_table('recetas')
    # ### end Alembic commands ###
