"""Se agregaron indices a las columnas de fecha de las tablas clientes, recetas y transacciones

Revision ID: dc9c39293931
Revises: 04e9eca1bcfc
Create Date: 2026-04-16 14:12:26.041624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc9c39293931'
down_revision: Union[str, Sequence[str], None] = '04e9eca1bcfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clientes_fecha_registro'), 'clientes', ['fecha_registro'], unique=False)
    op.create_index(op.f('ix_recetas_fecha_creacion'), 'recetas', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_transacciones_fecha_pago'), 'transacciones', ['fecha_pago'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacciones_fecha_pago'), table_name='transacciones')
    op.drop_index(op.f('ix_recetas_fecha_creacion'), table_name='recetas')
    op.drop_index(op.f('ix_clientes_fecha_registro'), table_name='clientes')
    # ### end Alembic commands ###
