"""Se agrego la tabla usuarios para la auntetificacion

Revision ID: ddda4cd3c0b1
Revises: 9fa98f4b2f7e
Create Date: 2026-03-03 21:56:16.613591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddda4cd3c0b1'
down_revision: Union[str, Sequence[str], None] = '9fa98f4b2f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo_electronico', sa.String(length=50), nullable=False),
    sa.Column('contrasenia', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'VENDEDOR', 'CAJA', name='rolenum'), nullable=False),
    sa.Column('fecha_registro', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
